  ---
- hosts: 127.0.0.1
  become: yes
  
   vars_prompt:
      - name: service_name
        prompt: "Name of service: "
        private: no
      - name: user
        prompt: "Username of new user: "
        private: no
      - name: group
        prompt: "Groupname of new user: "
        private: no
      - name: start_command
        prompt: "Command which need to be executed to start process: "
        private: no
      - name: stop_command
        prompt: "Command which need to be executed to stop process: "
        private: no
      - name: restart_command
        prompt: "Command which need to be executed to restart process: "
        private: no

    tasks:
      - name: "Create {{ service_name }} group"
          group:
            name: "{{ group }}"

        - name: "Create {{ service_name }} user"
          user:
            name: "{{ user }}"
            shell: /bin/false
            group: "{{ group }}"

        - name: Create systemd service file
          template:
            src: ../templates/template.service
            dest: "/etc/systemd/system/{{ service_name }}.service"
            owner: "{{ user }}"
            group: "{{ group }}"
            mode: 0744

        - name: reload system daemons
          command:
            cmd: systemctl daemon-reload

        - name: "Enable {{ service_name }}.service"
          systemd:
            name: "{{ service_name }}.service"
            enabled: true

        - name: "Start {{ service_name }}.service"
          systemd:
            name: "{{ service_name }}.service"
            state: started
